version: '2'

services:
    portainer:
        image: portainer/portainer
        restart: always
        container_name: "portainer-app"
        command: --host=unix:///var/run/docker.sock
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/portainer/data:/data